/* Original coaching materials. Personal facts supplied by the learner; story details are editable drafts. */
window.IELTS_SPRINT = {
  exam:'2026-11-29',
  profile:'济源人，现居北京，在京东做数据分析。喜欢徒步和健身，每月约两次爬山。去过尼泊尔 ABC、意大利多洛米蒂、香港麦理浩径、川西和张家口；在 ABC 看过日照金山、认识了朋友。用 Claude 提高工作效率，对 AI 与职业成长感兴趣。',
  order:'剑18恢复与诊断 → 剑19巩固 → 剑17/16按错因补弱项 → 剑20保留为11月首次模考。剑4–15只抽弱题型，不从4一路刷到20。已做过的套题可复练，但不能当首次成绩。',
  days:[
    ['2026-10-01',18,1,'恢复基线','工作/家乡/北京；ABC 日照金山','方法视频最多90分钟；听读各一套，今天晚了可将复盘移至明早'],
    ['2026-10-02',18,2,'拼写与定位','徒步/健身；徒步认识的朋友','优先完成昨天复盘；填空查单复数，阅读每题写证据'],
    ['2026-10-03',18,3,'干扰项与判断题','科技/学习；Claude 提效','听力记录答案被改口处；阅读分清 FALSE 与 NOT GIVEN'],
    ['2026-10-04',18,4,'第一次完整模拟','旅行/照片；多洛米蒂','听读写连续完成；口语做陌生题冷答'],
    ['2026-10-05',19,1,'最低科突破','城市/环境；麦理浩径','只选最高频的两类错因专项；不要再泛听长视频'],
    ['2026-10-06',19,2,'速度与准确率','挑战/计划；川西旅行','阅读记录三篇用时；练60秒准备与120秒回答'],
    ['2026-10-07',19,3,'第二次完整模拟','运动/工作；张家口周末徒步','首次成绩与10月1日对照；写作交老师或AI反馈后重写'],
    ['2026-10-08',19,4,'回炉与收口','随机抽题，复述全部8个故事','若错题积压超过两套，暂停新套题，全天复盘；建立返工后的学习节奏']
  ],
  videos:[
    {title:'刘洪波：阅读突击课第一课',author:'学为贵刘洪波',url:'https://www.bilibili.com/video/BV1i14y1M7fk/',minutes:17,action:'看完马上做一篇阅读：每道题圈定位词和原文证据。'},
    {title:'王陆：听力选择配对题做题原则',author:'王陆雅思听力技巧课',url:'https://www.bilibili.com/video/BV1Fi421S7XC/?p=18',minutes:10,action:'看第18集即可；拿今天错题标出干扰项和最终答案。'},
    {title:'杨帅：口语词汇多样性',author:'学为贵',url:'https://www.bilibili.com/video/BV1ji4y1U7v2/',minutes:60,action:'先看20分钟；选3个表达，用自己的工作或徒步故事录音重答。其余按需看。'},
    {title:'顾家北公开课：雅思写作高分的7大规律',author:'顾家北饥饿英语',url:'https://www.bilibili.com/video/BV15S6zY5E2x/',minutes:null,action:'写作选看；先审题写提纲，再用一段正文练观点、解释和例子。时长以播放页为准。'},
    {title:'刘洪波：阅读单选题',author:'学为贵刘洪波',url:'https://www.bilibili.com/video/BV1xx4y1T7oH/',minutes:16,action:'仅在单选是弱项时补看；逐一写出干扰选项错在哪里。'}
  ],
  sources:[['官方口语结构与评分','https://ielts.org/take-a-test/test-types/ielts-academic-test/ielts-academic-format-speaking'],['官方：避免机械背答案','https://ielts.org/news-and-insights/dont-overdo-it-how-to-ace-your-ielts-speaking-test'],['剑20音频与答案资源说明','https://shop.cambridge.org/english/product/2700250101'],['Cambridge One 配套资源','https://www.cambridgeone.org/']],
  speaking:[]
};
(function(){
const cards=window.IELTS_SPRINT.speaking;
const add=(part,title,q,answer,keys,tags,note='')=>cards.push({id:'sp'+(cards.length+1),part,title,q,answer,keys,tags,note});
const p1=[
['工作','What do you do?','I work as a data analyst at JD.com in Beijing. Basically, I turn numbers into useful information so that people can make better business decisions. It can get pretty busy, but I enjoy figuring out what the data is trying to tell us.','data analyst / numbers / decisions','work'],
['喜欢工作什么','What do you like about your job?','I like the moment when a confusing problem finally makes sense. Looking at a spreadsheet all day sounds a bit dull, but finding a pattern is surprisingly satisfying. I also like explaining it in plain language.','pattern / satisfying / explain','work'],
['工作压力','Is your work stressful?','Yes, especially when several tasks arrive at once. Recently I was so busy that my English study slipped down my priority list. Hiking helps me switch off, although I cannot exactly climb a mountain between meetings.','busy / priorities / switch off','work'],
['职业变化','Would you like to change your job?','I would like my work to become more strategic. I have been using AI tools to improve my efficiency, and that has made me curious about how my role might change. I still enjoy working with data, but I want to do more with the insights.','AI / efficiency / strategic','work'],
['家乡','Where is your hometown?','I am from Jiyuan in Henan Province. It is much smaller than Beijing, where I live now. For me, it is associated with familiarity and a slower pace of life, so going back feels like pressing a reset button.','Jiyuan / smaller / reset','hometown'],
['家乡变化','Has your hometown changed?','I would need to think of a specific example, but the biggest difference for me is how I see it now. After living in Beijing, I appreciate the calmer pace much more. Things I used to take for granted now feel quite special.','perspective / calmer / appreciate','hometown'],
['现居城市','Do you like living in Beijing?','Yes, because it gives me plenty of choices, both professionally and in my free time. I can have a busy working week and still go hiking nearby at the weekend. The crowds can be tiring, though, so I try to get outdoors regularly.','choices / hiking / crowds','city'],
['居住环境','What would you improve about your neighbourhood?','I would love to have more quiet green spaces within walking distance. After spending a day in front of a screen, I do not always want another noisy place. Somewhere simple to walk and clear my head would be ideal.','green space / screen / clear my head','home'],
['运动','What kind of exercise do you do?','I enjoy working out and hiking. The gym helps me build strength, and hiking gives me a chance to use it somewhere more interesting. I try to go into the mountains about twice a month.','strength / mountains / twice a month','fitness'],
['徒步','Why do you enjoy hiking?','It gives me a break from screens and deadlines. I like having one simple goal: keep moving and enjoy the view. My legs may be exhausted afterwards, but my brain usually feels much better.','screens / simple goal / tired legs','hiking'],
['周末','What do you usually do at weekends?','If I have enough time, I go hiking, often around Zhangjiakou. Otherwise, I might work out or take it easy. I enjoy being active, but I also appreciate a weekend with absolutely no complicated schedule.','Zhangjiakou / gym / take it easy','routine'],
['朋友','How do you make new friends?','Outdoor trips are a good way for me to meet people. I made quite a few friends on my ABC trek. Walking together gives you time to talk, and it feels more natural than trying to impress someone in a formal setting.','ABC / walk / natural','friends'],
['旅行','Do you like travelling?','Definitely. I am particularly drawn to places where I can spend time outdoors. I have been to the Dolomites, western Sichuan and Hong Kong’s MacLehose Trail. Each place has given me a different version of what a good hike can look like.','Dolomites / Sichuan / trail','travel'],
['照片','Do you take many photos?','When I travel, yes. I like taking photos of mountain scenery because the light changes so quickly. One image can bring back the feeling of being there, although a photo never quite captures the scale of a mountain.','light / memory / scale','photos'],
['科技','Do you often use technology?','Yes, it is part of both my work and my study. I use AI tools such as Claude, and I have built an IELTS study platform with AI help. I like technology most when it saves time and helps me do something practical.','Claude / study platform / practical','technology'],
['学习英语','Why are you learning English?','I want to do well in IELTS, but I also want to feel more comfortable talking to people when I travel. It could be useful for my career too. Having a clear exam date helps me turn a vague intention into a proper plan.','IELTS / travel / career','study'],
['时间安排','Are you good at managing your time?','At work, usually yes. With personal goals, I am still learning to be more consistent. My work got busy recently, so I am using the National Day break to get back into studying rather than waiting for a perfect moment.','work / consistency / holiday','time'],
['早起','Do you like getting up early?','It depends on the reason. Getting up for an ordinary working day is one thing; getting up to see a mountain sunrise is quite another. When I saw the golden light on the peaks during my ABC trek, the early start was worth it.','reason / sunrise / worth it','morning'],
['天气','What kind of weather do you like?','For hiking, I prefer clear weather with a cool breeze. It makes a long walk much more enjoyable and gives me a better view. I still check the forecast, because weather in the mountains can change quickly.','clear / breeze / forecast','weather'],
['放松','How do you relax?','I usually try to change my surroundings. After a week of working with data, being outdoors helps me stop thinking about unfinished tasks. Exercise also works well, especially when I am too busy for a proper trip.','surroundings / outdoors / exercise','relax'],
['独处','Do you prefer being alone or with others?','I enjoy both. I like having the freedom to make my own plans, but sharing a beautiful view with someone can make it more memorable. On a hike, a good conversation can make a long stretch feel much shorter.','freedom / shared view / conversation','friends'],
['未来计划','What would you like to learn in the future?','I would like to become more confident in English and learn more about AI. Both are relevant to the way I work and the things I enjoy outside work. I prefer learning something that I can actually use soon afterwards.','English / AI / use it','future'],
['数字','Are you good with numbers?','I work with numbers every day, so I am fairly comfortable with them. What I enjoy more, though, is understanding what they mean. A number becomes useful when it helps answer a real question.','comfortable / meaning / question','numbers'],
['假期','How do you spend your holidays?','I often like to travel or go hiking, but this National Day break is mainly for IELTS preparation. It is a different kind of challenge. I am trying to keep some exercise in the schedule so that I do not spend eight days glued to my chair.','IELTS / challenge / exercise','holiday']
];
p1.forEach(x=>add(1,x[0],x[1],x[2],x[3],x[4]));
const stories=[
['ABC 日照金山','Describe a beautiful natural place you have visited.','I would like to talk about the mountains I saw during my trek to Annapurna Base Camp in Nepal, which people often call ABC. I love hiking, and I have been to quite a few different places, but this experience really stands out.\n\nThe moment I remember most clearly was seeing the first sunlight turn the snowy peaks golden. The mountains looked enormous, and the light made everything feel almost unreal. I had seen photographs of scenery like that before, but actually standing there was very different. A photo gives you the view; being there gives you the scale.\n\nWhat also made the trip special was the people I met. I made quite a few friends during the trek. We shared the same route and the same excitement about the mountains, which gave us something to connect over straight away.\n\nMy normal life in Beijing involves a lot of screens and data, so this was a complete change of pace. For a while, I was simply paying attention to what was in front of me. I would happily go back, but I would not expect exactly the same experience. The combination of the light, the place and the people made that particular trip memorable.','Nepal → trek → golden peaks → new friends → screens to scenery','place,travel,photo,happy experience','真实核心：ABC、日照金山、交朋友。日期、同行人和天气请按实际补充。'],
['徒步中认识的朋友','Describe a person you enjoyed spending time with.','I would choose one of the friends I met during my ABC trek in Nepal. I made quite a few friends on that trip, but I would focus on one person whose company I particularly enjoyed.\n\nWhat I enjoyed was that we already had something in common: we both wanted to be out in the mountains. That made it easy to start a conversation. We did not have to invent an impressive introduction or talk only about our jobs. The route and the scenery gave us plenty to discuss.\n\nFor me, walking with someone is a relaxed way to get to know them. A conversation can continue for a while, then stop naturally when you are enjoying the view. There is no pressure to fill every silence. I think that is one reason I connected with people on the trip.\n\nI live in Beijing and work as a data analyst, so a lot of my weekday interactions are linked to tasks and deadlines. Meeting people through hiking felt different. We were sharing an experience that we had chosen for ourselves.\n\nI remember this person as a travel friend who made the journey more enjoyable. The nicest part was the sense of connection. The trip gave me wonderful scenery, but it also reminded me how much the people you meet can add to a journey.','shared interest → easy conversation → comfortable silence → connection','person,friend,conversation,travel','请把第一段改为一个真实朋友，补昵称、职业和一次真实交流；没有的信息不要背成事实。'],
['多洛米蒂旅行','Describe a trip you would like to take again.','I would like to visit the Dolomites in Italy again. I have already been there, and it is one of the places I associate most strongly with being outdoors. I am drawn to mountain landscapes, so it suited me very well.\n\nWhen I think about a good trip, I do not only think about how many famous sights I can fit into a day. I also think about whether I have time to enjoy the place. In the Dolomites, the scenery itself was a reason to slow down. I wanted to look around instead of constantly checking what was next on a schedule.\n\nI have also travelled to places such as western Sichuan and Nepal. They are all connected with my interest in the outdoors, but I would not say they feel the same. Visiting another mountain area gives me a fresh experience even when the activity is familiar.\n\nIf I returned to the Dolomites, I would plan enough time for walking and leave some flexibility in the itinerary. I would also choose one or two places to spend longer in, rather than try to see everything.\n\nIt is a trip I would repeat because it matches the kind of holiday I enjoy. I spend plenty of time analysing information at work. On a holiday, it is lovely to have something beautiful to look at without having to put it into a spreadsheet.','Italy → mountains → slow down → flexible itinerary → spreadsheet joke','trip,holiday,place,plan','路线、住宿、天气和同伴未提供；加一段你亲历的具体场景会更鲜活。'],
['麦理浩径与香港','Describe an outdoor activity you enjoyed.','I would like to describe hiking on the MacLehose Trail in Hong Kong. I enjoy hiking regularly, and this is one of the trips I have actually done. What interests me about it is the connection between a well-known city and its outdoor spaces.\n\nWhen people talk about Hong Kong, they often focus on the city. My experience included a different side of it because I went there to spend time on a trail. That gave me another way to remember the place. I like discovering somewhere through an activity rather than only through a list of attractions.\n\nHiking is enjoyable for me because the goal is straightforward. You move along the route, pay attention to your surroundings, and deal with whatever the walk requires. It is quite a change from my job in data analysis, where there may be several competing questions at the same time.\n\nI also liked having a trip that connected with a familiar interest. I hike regularly around Zhangjiakou, so walking in Hong Kong gave me a different setting for something I already enjoy. That is one of the reasons I like taking my hobbies with me when I travel.\n\nThe main reason I remember this activity is that it fitted my interests so well. I got to explore a place through movement. It also reminded me that a city trip and an outdoor trip do not have to be two completely separate choices.','Hong Kong → trail → different side → simple goal → explore on foot','activity,city,exercise,travel','请补你实际走的段数与场景；补一段亲历的景色或小事，会比泛讲徒步更生动。'],
['张家口的周末','Describe something you do to stay healthy.','One thing I do to stay healthy is go hiking regularly. I try to get out into the mountains about twice a month, and I have walked in quite a few places around Zhangjiakou. It gives me a routine that I actually look forward to.\n\nI work as a data analyst in Beijing, so a normal working day involves a lot of sitting and screen time. Hiking changes both of those things. I am moving for a long stretch, and I have something to focus on apart from work. I also enjoy working out, which helps me feel stronger when I go outdoors.\n\nThe appeal is not only physical. When I am walking, I can pay attention to a simple activity instead of jumping between messages and unfinished tasks. I may finish with tired legs, but I often feel mentally refreshed. That makes the time worthwhile.\n\nI do not treat every hike as a competition. The route needs to suit the conditions and the people taking part. Keeping the habit enjoyable matters more to me than making every outing longer or harder.\n\nI think this routine works because it fits my personality. I like exploring places and being active. Health feels less like another item on a to-do list when it comes from something I genuinely want to do.','twice a month → Zhangjiakou → desk job → physical + mental → enjoyable habit','health,routine,activity,relaxation','选一座你真实爬过的山作为例子；别把健康话题全变成旅游介绍。'],
['Claude 与学习平台','Describe a useful piece of technology.','I would like to talk about an AI assistant called Claude. I have used it to improve my efficiency at work, and that has made me much more interested in what AI tools can do. As a data analyst, I spend a lot of time working with information, so a tool that helps me handle it more effectively is relevant to my everyday life.\n\nWhat I value most is being able to move from a question to a useful starting point more quickly. I still need to understand the result and check whether it makes sense. Having an answer appear quickly does not mean I should automatically trust it. That checking process is part of using the tool well.\n\nMy interest in AI has also gone beyond work. I used AI help to build an IELTS study platform. Now I want it to organise my practice, keep track of mistakes and help me prepare speaking material based on my own experiences. It makes the technology feel practical.\n\nAt the same time, the speed of development has made me think about my career. I want to keep learning so that I can use these tools effectively and bring my own judgement to the work.\n\nSo I would call this technology useful because it saves time and encourages me to try new things. For me, the most satisfying part is turning an idea into something I can actually use.','Claude → efficiency → check results → IELTS platform → keep learning','technology,skill,learning,work,change','可补一个不含公司机密的真实使用例子，不编造提效百分比。'],
['川西与旅行计划','Describe a place you would recommend to a friend.','I would recommend western Sichuan to a friend who enjoys outdoor travel. I have been there myself, and it is one of the places I connect with my interest in mountain scenery. I would be more careful about recommending it to someone who wants only a very relaxed city holiday.\n\nFor me, choosing a destination starts with thinking about the kind of experience I want. I like being active and spending time outdoors. Western Sichuan fits that preference, so I would explain the trip in those terms instead of simply saying that everyone should go.\n\nI would also ask my friend about their fitness level, their available time and what they enjoy doing. Those things can make a big difference to the itinerary. Even if two people like the same scenery, they may want very different daily schedules.\n\nI would use my own route as a starting point, then explain which parts I would repeat and which I would adjust. I would also suggest checking current conditions before finalising a plan. A recommendation is more useful when it includes practical considerations as well as enthusiasm.\n\nThe main reason I would recommend the area is that it gave me the kind of outdoor experience I enjoy. I would love to share that interest with a friend, while helping them choose a trip that suits them.','western Sichuan → outdoor friend → fitness/time → practical itinerary','place,advice,travel,planning','请填真实地点与最喜欢的一幕；本稿避免臆造你的具体路线。'],
['国庆重启英语','Describe a goal you are working towards.','A goal I am working towards is getting an overall IELTS score of 6.5. My exam is at the end of November, and I am taking the Academic test on a computer. Having a specific date makes the goal feel much more concrete.\n\nI have some English foundations. I have studied vocabulary and I can manage basic conversations, but I have not taken IELTS before. That means I need to find out how I perform on real practice tests rather than guess from my previous English exams.\n\nRecently, work became very busy and I did not have much time to study. I am using the eight-day National Day break to restart. My main priorities are doing Cambridge practice tests, understanding my mistakes and speaking English every day.\n\nFor speaking, I want to use my own experiences. I have plenty to talk about, including my work in data analysis and trips to the mountains. The challenge is expressing those ideas clearly without depending on a script.\n\nAfter the holiday, I will need a routine that fits around work. I am treating the break as a strong start rather than expecting eight days to solve everything. Reaching this goal would be satisfying, but being more confident when I travel or communicate at work would matter to me as well.','6.5 → Nov 29 → busy work → holiday restart → sustainable routine','goal,challenge,learning,decision','这篇可直接按你已确认的事实改写；目标不是8天保证出分。']
];
stories.forEach(x=>add(2,...x));
const adaptations=[
 ['Describe a memorable journey. → 增加路线与过程','Describe a photograph you like. → 开头明确照片，再讲拍摄时刻','Describe a time you felt happy. → 聚焦看到金色山峰时的感受'],
 ['Describe a conversation you enjoyed. → 补一段真实对话','Describe a person you would like to travel with. → 解释相处舒适的原因','Describe a time you met someone new. → 说清认识过程'],
 ['Describe a place you want to revisit. → 加想再去的具体地方','Describe an enjoyable holiday. → 加最喜欢的一天','Describe an interesting place abroad. → 讲风景与旅行感受'],
 ['Describe an outdoor activity. → 说清走哪一段','Describe a city you enjoyed visiting. → 先介绍香港，补城市体验','Describe something you did with others. → 用真实同行人和互动'],
 ['Describe a healthy habit. → 聚焦规律与身体感受','Describe a place you go to relax. → 选一座张家口的山','Describe a weekend you enjoyed. → 讲一次具体周末'],
 ['Describe a useful skill you learned. → 聚焦学会使用AI的过程','Describe a positive change. → 用一个真实提效例子','Describe something you made. → 聚焦雅思平台制作过程'],
 ['Describe advice you gave. → 只有真实给过建议才改成过去式','Describe a trip you planned. → 用实际路线、安排和调整','Describe a beautiful place in your country. → 选川西真实地点'],
 ['Describe a challenge. → 解释工作忙与学习之间的冲突','Describe an important decision. → 聚焦重新开始备考的选择','Describe something you want to improve. → 聚焦口语与未来用途']
];
const followups=[
 ['Why do people enjoy visiting mountains?','How can tourism protect natural places?'],
 ['Is it easier to make friends while travelling?','Are shared interests enough for a lasting friendship?'],
 ['Why do some people revisit the same destination?','How has international travel changed people’s lives?'],
 ['Should cities provide more outdoor spaces?','What makes an activity suitable for different ages?'],
 ['Why do people find it hard to exercise regularly?','Who should encourage healthy habits?'],
 ['How might AI change work?','Should schools teach people to check AI-generated information?'],
 ['What makes travel advice useful?','Is careful planning always necessary?'],
 ['Why do some people give up their goals?','How should people balance long-term goals and daily responsibilities?']
];
cards.filter(c=>c.part===2).forEach((c,i)=>{c.adaptations=adaptations[i];c.followups=followups[i];});
const p3=[
['户外与健康','Why are outdoor activities popular?','They offer a change from everyday routines. Many people spend hours indoors or looking at screens, so being outside can feel refreshing. There is also a social side: a shared activity gives people something to do together. Of course, preferences vary, and not everyone wants a physically demanding trip.','routine → screens → social → exception','outdoors'],
['城市绿地','Should cities provide more green spaces?','Yes, especially in neighbourhoods where people have few places to walk or relax. A small accessible park can be useful every day, while a large park far away may only be visited occasionally. However, cities also need housing and transport, so good planning matters more than simply increasing the amount of green land.','access → daily use → land trade-off','city'],
['旅游与环境','How can tourism affect natural places?','It can bring money and jobs to local communities, but heavy visitor numbers can also create waste and damage trails. The balance depends on how tourism is managed. Clear rules, suitable facilities and limits in fragile areas may help. Visitors also need to take responsibility for their own behaviour.','income → damage → management → visitors','environment'],
['朋友与共同兴趣','Do shared interests help people become friends?','Usually, because they make starting a conversation easier. People have something concrete to discuss and a reason to spend time together. But shared interests are only a starting point. In the long run, reliability and the way people treat each other probably matter more.','conversation → time → reliability','friends'],
['AI与职业','Will AI replace people at work?','It will probably replace some tasks and change many roles. Routine work is easier to automate, while understanding a business problem or taking responsibility for a decision can be more complicated. In data analysis, for example, producing an initial result may become faster, but someone still needs to check what it means. The outcome will vary by job.','tasks → routine → judgement → variation','technology'],
['学习科技','Does technology always improve learning?','No, the result depends on how it is used. A tool can give quick feedback and make practice convenient, but it can also encourage people to copy an answer without understanding it. For language learning, I would use technology to create more opportunities to speak and review mistakes. The learner still has to do the practice.','feedback → copying → practice','education'],
['年轻人与健康','Why do some people struggle to exercise regularly?','Time is one reason, especially when work and commuting take up most of the day. Another is choosing a routine that is too demanding to maintain. A small activity people enjoy may be easier to keep up than an ambitious plan. Cost and access to suitable places can matter as well.','time → unrealistic plan → enjoyment → access','health'],
['旅行方式','Is travelling alone better than travelling with others?','Neither is better for everyone. Travelling alone gives people more control over their plans, while travelling with others allows them to share experiences and support each other. The destination and the type of trip matter too. A flexible city break may be different from a demanding trek where teamwork is useful.','control → sharing → trip type','travel'],
['照片与记忆','Why do people take photographs when travelling?','They want to keep a record of experiences and share them with others. A photograph can bring back a memory quickly, especially if it captures a person or a particular moment. However, taking too many photos can distract people from the experience itself. There is a balance between recording a trip and enjoying it.','record → memory → distraction → balance','photos'],
['工作生活平衡','What can employers do to improve work-life balance?','They can set clearer priorities and more realistic deadlines. If everything is treated as urgent, employees may struggle to switch off even after leaving the office. Flexibility can help as well, but it is less useful if the workload remains excessive. Managers need to look at both the schedule and the actual amount of work.','priorities → deadlines → flexibility → workload','work'],
['技能与考试','Are exams a good way to measure ability?','They are useful because they provide a common task and a consistent way to compare performance. But one exam cannot capture every aspect of a person’s ability. Someone may know a subject well and still struggle under time pressure. I would combine exam results with practical work when possible.','consistent → incomplete → pressure → combine','education'],
['家乡和大城市','Why do people move to large cities?','Employment and education are common reasons. Large cities may offer more choices and make it easier to meet people in a particular field. The trade-off is that housing, commuting and daily life can be more demanding. Whether moving is worthwhile depends on what a person wants and what they are giving up.','opportunity → connections → cost → individual','city'],
['计划与灵活性','Is it important to plan a trip carefully?','Yes, especially for transport, accommodation and safety. Good planning reduces avoidable stress. But I would still leave some flexibility for weather or unexpected discoveries. The aim is to make the trip smoother, rather than give every minute a fixed instruction.','essentials → stress → flexibility','planning'],
['榜样','What makes someone a good role model?','Their actions should match the values they talk about. Achievement can be inspiring, but the way they treat others matters too. I would also prefer a role model who admits mistakes and keeps learning. That makes their example more realistic and easier for other people to learn from.','actions → respect → admit mistakes','people'],
['政府与运动','Should governments encourage people to exercise?','Yes, but support needs to be practical. Safe walking routes and affordable sports facilities can make exercise easier to fit into daily life. Information campaigns may help, but they have limited value if people cannot access suitable places. I would focus on removing barriers as well as giving advice.','safe routes → affordable → remove barriers','health'],
['广告与消费','How does online advertising influence shopping?','It can introduce people to products they might not have found themselves. Recommendations also make shopping convenient, but they can encourage unnecessary purchases. People may confuse a repeated message with a genuine need. I think it helps to pause and compare options before making a decision.','discovery → convenience → unnecessary → pause','shopping']
];
p3.forEach(x=>add(3,x[0],x[1],x[2],x[3],x[4]));
})();
