(()=>{'use strict';
const KEY='ielts-word-adventure-v1', $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
let S;try{S=JSON.parse(localStorage.getItem(KEY))}catch{}if(!S||S.version!==1)S={version:1,start:day(),cards:{},read:{},reviews:{},xp:0,custom:[],imported:[],voice:'en-GB'};
S.custom??=[];S.imported??=[];let selected='',quiz=null,choice='';
const save=()=>{localStorage.setItem(KEY,JSON.stringify(S))};const lessons=()=>[...window.IELTS_WORD_ARTICLES,...S.custom];
const daily=()=>lessons()[Math.max(0,Math.floor((Date.parse(day())-Date.parse(S.start))/86400000))%lessons().length];
let lessonId=daily().id;const lesson=()=>lessons().find(l=>l.id===lessonId)||daily();
const key=w=>w.toLowerCase();const rx=w=>new RegExp('\\b'+w.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\b','gi');
const context=(l,w)=>l.paragraphs.join(' ').split(/(?<=[.!?])\s+/).find(s=>rx(w).test(s))||l.paragraphs[0];
function speak(text){if(!('speechSynthesis'in window)){alert('当前浏览器没有系统朗读，请使用手机 Safari 或 Chrome。');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=S.voice;u.rate=Number($('#wordSpeed')?.value||.85);u.voice=speechSynthesis.getVoices().find(v=>v.lang===S.voice)||null;speechSynthesis.speak(u)}
function mark(w,status,l=lesson()){const k=key(w.word),old=S.cards[k];S.cards[k]={...old,word:w.word,meaning:w.meaning,context:context(l,w.word),status,stage:status==='unknown'?0:old?.stage||0,due:status==='known'?(old?.due||day()):day()};save();render()}
function highlight(p,l){let re=new RegExp('\\b('+l.words.map(w=>w.word.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).sort((a,b)=>b.length-a.length).join('|')+')\\b','gi');let out='',at=0;for(const m of p.matchAll(re)){out+=esc(p.slice(at,m.index));out+=`<button class="word-token ${S.cards[key(m[0])]?.status==='unknown'?'unknown':''}" data-word="${esc(key(m[0]))}">${esc(m[0])}</button>`;at=m.index+m[0].length}return out+esc(p.slice(at))}
function streak(){let n=0,d=Date.parse(day());if(!S.read[day()]&&!S.reviews[day()])d-=86400000;for(;n<365;n++,d-=86400000){const date=new Date(d).toISOString().slice(0,10);if(!S.read[date]&&!S.reviews[date])break}return n}
function render(){const l=lesson(),due=Object.values(S.cards).filter(c=>c.status!=='known'||c.stage>0).filter(c=>c.due<=day()),w=l.words.find(w=>key(w.word)===selected)||Object.values(S.cards).find(w=>key(w.word)===selected);
$('#view-words').innerHTML=`<div class="word-hero"><div class="eyebrow">DAILY WORD EXPEDITION</div><h2>每天一篇，把单词读进故事里。</h2><p>15–20分钟：读文章 → 圈生词 → 回忆挑战 → 到期复习</p><div class="word-stats"><div><b>${S.xp}</b><span>回忆积分</span></div><div><b>${streak()}</b><span>连续学习天数</span></div><div><b>${due.length}</b><span>今天待复习</span></div><div><b>${Object.values(S.cards).filter(c=>c.stage>=3).length}</b><span>完成三轮回忆</span></div></div></div>
<div class="word-flex"><select id="wordLesson" class="word-nav-select" aria-label="选择每日文章">${lessons().map((a,i)=>`<option value="${esc(a.id)}" ${a.id===l.id?'selected':''}>${i+1}. ${esc(a.theme)} · ${esc(a.title)}${a.id===daily().id?' · 今日推荐':''}</option>`).join('')}</select><button class="btn" id="wordDaily">回到今日</button><button class="btn primary" id="wordChallenge">回忆挑战 · 最多8题</button></div>
<div id="wordQuiz" class="card word-quiz" style="display:${quiz?'block':'none'};margin-top:18px"></div>
<div class="word-layout" style="margin-top:18px"><article class="card"><div class="word-caption">${esc(l.source)} · ${l.words.length} 个目标词</div><h2>${esc(l.title)}</h2><div class="word-flex"><button class="btn" id="wordReadAudio">听整篇</button><button class="btn" id="wordStop">停止朗读</button><select id="wordVoice" aria-label="口音"><option value="en-GB" ${S.voice==='en-GB'?'selected':''}>英音</option><option value="en-US" ${S.voice==='en-US'?'selected':''}>美音</option></select><select id="wordSpeed" aria-label="朗读速度"><option value=".85">慢速 0.85×</option><option value="1">正常 1×</option></select></div><div class="word-story">${l.paragraphs.map(p=>`<p>${highlight(p,l)}</p>`).join('')}</div><button class="btn" id="wordReadDone">${S.read[day()]?.includes(l.id)?'✓ 今日已读':'读完本篇 · +5分'}</button><p class="word-note">点击绿色词查看释义和读音。朗读使用设备系统语音，首次播放需点击；文章为原创练习故事，部分情节虚构。</p></article>
<aside class="card word-panel"><div class="eyebrow">WORD EXPLORER</div>${w?`<h2>${esc(w.word)}</h2><p>${esc(w.meaning)}</p><p class="word-note">${esc(S.cards[key(w.word)]?.status==='unknown'?'已标记：不会':'点击状态记录熟悉程度；只有回忆答对才推进复习轮次。')}</p><div class="word-flex"><button class="btn" id="wordPronounce">🔊 单词读音</button><button class="btn" id="wordSentence">听例句</button></div><p>${esc(context(l,w.word))}</p><div class="word-flex"><button class="btn" data-mark="unknown">不会 · 加入复习</button><button class="btn" data-mark="shaky">模糊</button><button class="btn" data-mark="known">熟悉</button></div>`:'<h3>从文章里选一个词</h3><p>不会的词标成金色，下次回来继续复习。</p>'}<h4>本篇目标词</h4><div class="word-list">${l.words.map(x=>`<button class="btn smallbtn" data-word="${esc(key(x.word))}">${esc(x.word)}</button>`).join('')}</div></aside></div>
<details class="card word-import"><summary>导入《雅思词汇真经》词表 / 制作自己的文章</summary><p class="word-note">内置22篇按主题原创选词，未核对书内完整词表。粘贴你拥有的词表，每行“英文单词 | 中文释义”，最多4000词。分成每组12词，逐组生成或粘贴文章。</p><textarea id="wordImportText" rows="6" placeholder="glacier | 冰川\naltitude | 海拔"></textarea><div class="word-flex"><input type="file" id="wordImportFile" accept=".txt,.csv,.tsv"><button class="btn" id="wordImport">导入词表</button></div><p id="wordImportMessage" role="status"></p><select id="wordBatch" aria-label="导入词表分组">${Array.from({length:Math.ceil(S.imported.length/12)},(_,i)=>`<option value="${i}">第${i+1}组：${esc(S.imported.slice(i*12,i*12+12).map(w=>w.word).join(', '))}</option>`).join('')}</select><div class="word-flex"><button class="btn" id="wordPrompt">复制文章提示词</button><button class="btn" id="wordGenerate">用已配置的AI生成</button></div><p class="word-note">AI按钮会把当前组的词和释义发送给设置页所选AI服务。无需API：复制提示词去你的AI聊天，生成后粘贴在下面。</p><textarea id="wordCustomText" rows="8" placeholder="粘贴原创英文文章，需包含本组每个原形词"></textarea><button class="btn" id="wordSaveArticle">检查覆盖并保存文章</button><p class="word-note"><a href="https://www.guixue.com/words/primary.shtml" target="_blank" rel="noopener">作者官方章节音频 ↗</a> · 生词、积分和文章保存在本机；换设备前请在设置页导出备份。</p></details>`;
$('#wordLesson').onchange=e=>{lessonId=e.target.value;selected='';quiz=null;render()};$('#wordDaily').onclick=()=>{lessonId=daily().id;quiz=null;render()};$('#wordVoice').onchange=e=>{S.voice=e.target.value;save()};$('#wordStop').onclick=()=>window.speechSynthesis?.cancel();$('#wordReadAudio').onclick=()=>speak(l.paragraphs.join(' '));
$('#wordReadDone').onclick=()=>{S.read[day()]??=[];if(!S.read[day()].includes(l.id)){S.read[day()].push(l.id);S.xp+=5;save()}render()};
$('#view-words').querySelectorAll('[data-word]').forEach(b=>b.onclick=()=>{selected=b.dataset.word;render()});if(w){$('#wordPronounce').onclick=()=>speak(w.word);$('#wordSentence').onclick=()=>speak(context(l,w.word));$('#view-words').querySelectorAll('[data-mark]').forEach(b=>b.onclick=()=>mark(w,b.dataset.mark,l))}
$('#wordChallenge').onclick=startQuiz;bindImport();if(quiz)renderQuiz();}
function startQuiz(){const due=Object.values(S.cards).filter(c=>c.due<=day()&&(c.status!=='known'||c.stage>0));const pool=[...due,...lesson().words.map(w=>({...w,context:context(lesson(),w.word)}))];const seen=new Set();quiz={queue:pool.filter(w=>!seen.has(key(w.word))&&seen.add(key(w.word))).slice(0,8).map((w,i)=>({...w,mode:i%2===0?'cloze':'spell'})),i:0,right:0,total:Math.min(8,new Set(pool.map(w=>key(w.word))).size),feedback:null,failed:new Set(),retry:new Set()};render();$('#wordQuiz').scrollIntoView({behavior:'smooth',block:'start'})}
function renderQuiz(){const q=quiz,box=$('#wordQuiz');if(q.i>=q.queue.length){box.innerHTML=`<h3>本轮结束 · ${q.right} 次正确回忆</h3><p>答错的词已安排明天复习。正确词按1 / 3 / 7 / 14 / 30天间隔回炉。</p><button class="btn" id="wordQuizClose">返回文章</button>`;$('#wordQuizClose').onclick=()=>{quiz=null;render()};return}
const w=q.queue[q.i];choice=w.word;const alternatives=[w.word,...lesson().words.map(x=>x.word).filter(x=>key(x)!==key(w.word)).slice(0,3)].sort(()=>Math.random()-.5);
box.innerHTML=`<div class="word-flex"><h3>回忆挑战 ${q.i+1} / ${q.queue.length}</h3><button class="btn" id="wordQuizClose">退出</button></div>${w.mode==='cloze'?`<p>${esc(w.context).replace(rx(w.word),'_____')}</p><p class="word-note">提示：${esc(w.meaning)}</p><div class="word-options">${alternatives.map(a=>`<button class="btn" data-answer="${esc(a)}" ${q.feedback?'disabled':''}>${esc(a)}</button>`).join('')}</div>`:`<p>先点击听音，再拼出单词。释义提示：${esc(w.meaning)}</p><button class="btn" id="wordQuizAudio">🔊 听单词</button><input id="wordSpell" autocomplete="off" autocapitalize="none" spellcheck="false" placeholder="输入英文" ${q.feedback?'disabled':''}><button class="btn" id="wordSubmit" ${q.feedback?'disabled':''}>检查</button>`}${q.feedback?`<div class="word-feedback"><b>${q.feedback.correct?'✓ 回忆成功':'再看一次，稍后重试'}</b><p>${esc(w.word)} · ${esc(w.meaning)}</p><p>${esc(w.context)}</p><button class="btn" id="wordFeedbackAudio">听正确读音</button></div><button class="btn primary" id="wordNext">下一题</button>`:''}`;
$('#wordQuizClose').onclick=()=>{quiz=null;render()};box.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(b.dataset.answer));if($('#wordQuizAudio')){$('#wordQuizAudio').onclick=()=>speak(w.word);$('#wordSubmit').onclick=()=>answer($('#wordSpell').value);$('#wordSpell').onkeydown=e=>{if(e.key==='Enter')answer(e.target.value)}}if(q.feedback){$('#wordFeedbackAudio').onclick=()=>speak(w.word);$('#wordNext').onclick=()=>{q.i++;q.feedback=null;renderQuiz()}}}
function answer(value){if(!quiz||quiz.feedback)return;const q=quiz,w=q.queue[q.i],k=key(w.word),correct=value.trim().toLowerCase()===k;let c=S.cards[k]||{word:w.word,meaning:w.meaning,context:w.context,status:'shaky',stage:0};if(correct){q.right++;if(c.lastReview!==day()){c.stage=q.failed.has(k)?0:Math.min(5,c.stage+1);c.due=new Date(Date.parse(day())+[1,1,3,7,14,30][c.stage]*86400000).toISOString().slice(0,10);c.lastReview=day();S.xp+=10}}else{q.failed.add(k);c.stage=0;c.status='unknown';c.due=new Date(Date.parse(day())+86400000).toISOString().slice(0,10);if(!q.retry.has(k)){q.retry.add(k);q.queue.push({...w,mode:'spell'})}}S.cards[k]=c;S.reviews[day()]=(S.reviews[day()]||0)+1;save();q.feedback={correct};renderQuiz()}
function batch(){return S.imported.slice(Number($('#wordBatch').value)*12,Number($('#wordBatch').value)*12+12)}
function prompt(){const b=batch();if(!b.length)throw Error('请先导入词表');return 'Write an original coherent 180–250 word IELTS learner story, B1–B2 level, about hiking, health, or a Beijing data analyst. Include every exact English word/phrase below at least once (no inflection-only substitutions). Use natural grammar and clear paragraphs. Return only the article, no title or word list. Words and meanings: '+b.map(w=>w.word+'='+w.meaning).join('; ')}
function bindImport(){const message=t=>$('#wordImportMessage').textContent=t;$('#wordImportFile').onchange=async e=>{const f=e.target.files[0];if(f)$('#wordImportText').value=await f.text()};$('#wordImport').onclick=()=>{const lines=$('#wordImportText').value.split(/\r?\n/).filter(x=>x.trim());let bad=0;const map=new Map(S.imported.map(w=>[key(w.word),w]));for(const line of lines){const m=line.trim().match(/^([a-zA-Z][a-zA-Z '-]{0,70})\s*(?:\||\t|,|，|：|:)\s*(.+)$/);if(!m){bad++;continue}const word=m[1].trim();map.set(key(word),{word,meaning:m[2].trim()})}if(map.size>4000){message('最多导入4000词，请分批。');return}S.imported=[...map.values()];save();render();$('.word-import').open=true;$('#wordImportMessage').textContent=`已存${S.imported.length}词，${bad}行未识别。选择一组制作文章。`};$('#wordPrompt').onclick=async()=>{try{const p=prompt();try{await navigator.clipboard.writeText(p);message('提示词已复制')}catch{$('#wordCustomText').value=p;message('复制不可用，提示词已放在下方，请手动复制')}}catch(e){message(e.message)}};
$('#wordGenerate').onclick=async e=>{const b=e.target;try{const p=prompt();if(!window.IELTSAI?.getKey())throw Error('请先在设置页配置AI，或复制提示词到你的AI聊天。');b.disabled=true;b.textContent='生成中…';const text=await window.IELTSAI.generateText(p,{temperature:.7,maxOutputTokens:1200});$('#wordCustomText').value=text.replace(/^```[^\n]*\n|```$/g,'').trim();message('已生成。请阅读检查，再点击检查覆盖并保存。')}catch(err){message(err.message)}finally{b.disabled=false;b.textContent='用已配置的AI生成'}};
$('#wordSaveArticle').onclick=()=>{const b=batch(),text=$('#wordCustomText').value.trim();if(!b.length||text.length<120){message('请导入词表，并粘贴一篇完整英文文章。');return}const missing=b.filter(w=>!rx(w.word).test(text));if(missing.length){message('缺少原形词：'+missing.map(w=>w.word).join(', '));return}const custom={id:'custom-'+Date.now(),theme:'我的词表',title:'My Word Expedition '+(S.custom.length+1),words:b,paragraphs:text.split(/\n+/).filter(Boolean),source:'用户导入词表 · 自定义文章，释义与内容请自行核对'};S.custom.push(custom);save();lessonId=custom.id;selected='';render();message('文章已保存')};}
function open(){window.IELTSOpenView('words');$('#topTitle').textContent='每日单词';render()}
const view=document.createElement('section');view.id='view-words';view.className='view';$('.content').append(view);for(const id of ['desktopNav','mobileNav']){const nav=$('#'+id);if(nav){const b=document.createElement('button');b.dataset.view='words';b.textContent='📖 每日单词';b.onclick=open;nav.append(b)}}
window.IELTSWords={open,export:()=>S};render();
})();
