(()=>{'use strict';
const KEY='ielts-word-adventure-v1', $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
let S;try{S=JSON.parse(localStorage.getItem(KEY))}catch{}if(!S||S.version!==1)S={version:1,start:day(),cards:{},read:{},reviews:{},xp:0,custom:[],imported:[],voice:'en-GB'};
S.custom??=[];S.imported??=[];let selected='',quiz=null,choice='';
const save=()=>{localStorage.setItem(KEY,JSON.stringify(S))};const lessons=()=>[...window.IELTS_WORD_ARTICLES,...S.custom];
const daily=()=>lessons()[Math.max(0,Math.floor((Date.parse(day())-Date.parse(S.start))/86400000))%lessons().length];
let lessonId=daily().id;const lesson=()=>lessons().find(l=>l.id===lessonId)||daily();
const key=w=>w.toLowerCase();const rx=w=>new RegExp('\\b'+w.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\b','gi');
const context=(l,w)=>l.paragraphs.join(' ').split(/(?<=[.!?])\s+/).find(s=>rx(w).test(s))||l.paragraphs[0];
// Keep the media element and utterance alive when the article panel rerenders.
let audioDock=null, audioPlayer=null, activeUtterance=null, audioRun=0, startTimer=null;
function audioUI(){if(audioDock)return;audioDock=document.createElement('aside');audioDock.id='wordAudioDock';audioDock.hidden=true;audioDock.style.cssText='position:fixed;bottom:88px;left:12px;right:12px;z-index:50;background:#fff;border:2px solid #287568;border-radius:16px;padding:12px;box-shadow:0 8px 32px #0003;max-width:540px;margin:auto';audioDock.innerHTML='<div style="display:flex;gap:8px;align-items:center"><b id="wordAudioLabel" style="flex:1;overflow-wrap:anywhere">读音播放器</b><button id="wordAudioClose" class="btn">关闭</button></div><audio id="wordMediaPlayer" controls playsinline preload="none" style="width:100%;margin-top:8px"></audio><p style="font-size:13px;margin:6px 0">iPhone 无声时，请按播放器 ▶，并调高媒体音量；在线音频需要联网。</p><p id="wordAudioStatus" role="status" style="margin:6px 0;font-size:13px"></p><div style="display:flex;gap:12px;flex-wrap:wrap"><button id="wordGPTAudio" class="btn smallbtn">GPT 生成 MP3</button><button id="wordSystemRetry" class="btn smallbtn">改用系统朗读</button><a id="wordAudioDirect" target="_blank" rel="noopener">单独打开音频 ↗</a></div>';document.body.append(audioDock);audioPlayer=$('#wordMediaPlayer');$('#wordAudioClose').onclick=()=>{stopAudio();audioDock.hidden=true};$('#wordGPTAudio').onclick=()=>window.IELTSVoiceLab?.tts(audioDock.dataset.text||'').catch(e=>audioStatus(e.message));$('#wordSystemRetry').onclick=()=>systemSpeak(audioDock.dataset.text||'');}
function audioStatus(t){audioUI();$('#wordAudioStatus').textContent=t}
function stopAudio(){audioRun++;clearTimeout(startTimer);audioPlayer?.pause();if(audioPlayer)audioPlayer.onended=null;window.speechSynthesis?.cancel();activeUtterance=null}
function systemSpeak(text){stopAudio();audioUI();audioPlayer.hidden=true;audioDock.hidden=false;audioDock.dataset.text=text;if(!window.speechSynthesis||!window.SpeechSynthesisUtterance){audioStatus('系统语音不可用，请用 GPT 生成音频，或选择单独打开单词音频。');return}const synth=window.speechSynthesis,run=audioRun,parts=text.split(/(?<=[.!?])\s+/).flatMap(x=>x.match(/.{1,140}(?:\s|$)|.{1,140}/g)||[x]);let at=0;const next=()=>{if(run!==audioRun)return;if(at>=parts.length){audioStatus('系统朗读结束。');activeUtterance=null;return}const u=activeUtterance=new SpeechSynthesisUtterance(parts[at]);u.lang=S.voice;u.rate=Number($('#wordSpeed')?.value||.85);u.volume=1;u.voice=synth.getVoices().find(v=>v.lang.replace('_','-')===S.voice)||null;u.onstart=()=>{clearTimeout(startTimer);audioStatus('系统朗读 '+(at+1)+' / '+parts.length+' · 英文合成语音')};u.onend=()=>{if(run===audioRun){at++;next()}};u.onerror=e=>{if(run===audioRun)audioStatus('系统语音失败：'+e.error+'。请使用 GPT 音频或检查 iPhone 英文语音。')};synth.resume();synth.speak(u);clearTimeout(startTimer);startTimer=setTimeout(()=>{if(run===audioRun)audioStatus('如无声，请点“改用系统朗读”重试，或配置 GPT 音频服务。')},6000)};next()}

function speak(text,hideWord=false){if(text.trim().includes(' '))return systemSpeak(text);stopAudio();audioUI();audioPlayer.hidden=false;$('#wordAudioDirect').textContent='单独打开音频 ↗';audioDock.hidden=false;audioDock.dataset.text=text;$('#wordAudioLabel').textContent=hideWord?'听音拼写 · 播放单词':text.length<60?'读音 · '+text:'例句 / 文章读音';let queue=[];for(const sentence of text.split(/(?<=[.!?])\s+/)){let part='';for(const w of sentence.trim().split(/\s+/)){if((part+' '+w).length>180){queue.push(part);part=w}else part+=(part?' ':'')+w}if(part)queue.push(part)}if(!queue.length)return;const run=audioRun,rate=Number($('#wordSpeed')?.value||.85);let at=0;const play=()=>{if(run!==audioRun)return;const url='https://dict.youdao.com/dictvoice?audio='+encodeURIComponent(queue[at])+'&type='+(S.voice==='en-US'?2:1);audioPlayer.src=url;audioPlayer.playbackRate=rate;audioPlayer.muted=false;audioPlayer.volume=1;$('#wordAudioDirect').href=url;audioStatus('加载在线音频 '+(at+1)+' / '+queue.length+'…');audioPlayer.onplaying=()=>{if(run===audioRun)audioStatus('正在播放 '+(at+1)+' / '+queue.length+' · 有道在线读音')};audioPlayer.onerror=()=>{if(run===audioRun)audioStatus('在线音频加载失败。可改用系统朗读，或单独打开音频。')};audioPlayer.onended=()=>{if(run!==audioRun)return;if(++at<queue.length)play();else audioStatus('播放结束。')};audioPlayer.play().catch(e=>{if(run!==audioRun)return;audioStatus(e.name==='NotAllowedError'?'浏览器阻止自动开始。请点击上方播放器的 ▶ 按钮。':'播放未开始，请点击 ▶ 重试，或改用系统朗读。')})};play()}

const articleCache={};async function readArticle(l){if(!/^theme-\d+$/.test(l.id))return systemSpeak(l.paragraphs.join(' '));stopAudio();audioUI();audioPlayer.hidden=false;audioDock.hidden=false;audioDock.dataset.text=l.paragraphs.join(' ');$('#wordAudioLabel').textContent='文章英音示范 · '+l.title;audioStatus('加载本站文章音频…');const run=audioRun;try{const group=Math.ceil(Number(l.id.split('-')[1])/4);articleCache[group]??=fetch('./article-audio-'+group+'.json').then(r=>{if(!r.ok)throw Error('文章音频暂未加载');return r.json()}).catch(e=>{delete articleCache[group];throw e});const item=(await articleCache[group])[l.id];if(run!==audioRun)return;if(!item||item.text!==l.paragraphs.join(' '))throw Error('文章已修改，请重新生成示范');audioPlayer.src=item.src;audioPlayer.muted=false;audioPlayer.volume=1;audioPlayer.playbackRate=Number($('#wordSpeed')?.value||1);audioPlayer.onplaying=()=>audioStatus('正在播放 · 本站预生成英音合成示范');audioPlayer.onended=()=>audioStatus('文章播放结束');audioPlayer.onerror=()=>audioStatus('音频解码失败，请切换系统朗读');$('#wordAudioDirect').removeAttribute('href');$('#wordAudioDirect').textContent='本篇音频已内置';audioPlayer.load();await audioPlayer.play()}catch(e){if(run===audioRun)audioStatus('请点击播放器 ▶ 开始；若无音频条可切换系统朗读。'+e.message)}}

function mark(w,status,l=lesson()){const k=key(w.word),old=S.cards[k];S.cards[k]={...old,word:w.word,meaning:w.meaning,context:context(l,w.word),status,stage:status==='unknown'?0:old?.stage||0,due:status==='known'?(old?.due||day()):day()};save();render()}
function highlight(p,l){let re=new RegExp('\\b('+l.words.map(w=>w.word.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).sort((a,b)=>b.length-a.length).join('|')+')\\b','gi');let out='',at=0;for(const m of p.matchAll(re)){out+=esc(p.slice(at,m.index));out+=`<button class="word-token ${S.cards[key(m[0])]?.status==='unknown'?'unknown':''}" data-word="${esc(key(m[0]))}">${esc(m[0])}</button>`;at=m.index+m[0].length}return out+esc(p.slice(at))}
function streak(){let n=0,d=Date.parse(day());if(!S.read[day()]&&!S.reviews[day()])d-=86400000;for(;n<365;n++,d-=86400000){const date=new Date(d).toISOString().slice(0,10);if(!S.read[date]&&!S.reviews[date])break}return n}
function render(){const l=lesson(),due=Object.values(S.cards).filter(c=>c.status!=='known'||c.stage>0).filter(c=>c.due<=day()),w=l.words.find(w=>key(w.word)===selected)||Object.values(S.cards).find(w=>key(w.word)===selected);
$('#view-words').innerHTML=`<div class="word-hero"><div class="eyebrow">DAILY WORD EXPEDITION</div><h2>每天一篇，把单词读进故事里。</h2><p>15–20分钟：读文章 → 圈生词 → 回忆挑战 → 到期复习</p><div class="word-stats"><div><b>${S.xp}</b><span>回忆积分</span></div><div><b>${streak()}</b><span>连续学习天数</span></div><div><b>${due.length}</b><span>今天待复习</span></div><div><b>${Object.values(S.cards).filter(c=>c.stage>=3).length}</b><span>完成三轮回忆</span></div></div></div>
<div class="word-flex"><select id="wordLesson" class="word-nav-select" aria-label="选择每日文章">${lessons().map((a,i)=>`<option value="${esc(a.id)}" ${a.id===l.id?'selected':''}>${i+1}. ${esc(a.theme)} · ${esc(a.title)}${a.id===daily().id?' · 今日推荐':''}</option>`).join('')}</select><button class="btn" id="wordDaily">回到今日</button><button class="btn primary" id="wordChallenge">回忆挑战 · 最多8题</button></div>
<div id="wordQuiz" class="card word-quiz" style="display:${quiz?'block':'none'};margin-top:18px"></div>
<div class="word-layout" style="margin-top:18px"><article class="card"><div class="word-caption">${esc(l.source)} · ${l.words.length} 个目标词</div><h2>${esc(l.title)}</h2><div class="word-flex"><button class="btn" id="wordReadAudio">听整篇</button><button class="btn" id="wordStop">停止朗读</button><select id="wordVoice" aria-label="口音"><option value="en-GB" ${S.voice==='en-GB'?'selected':''}>英音</option><option value="en-US" ${S.voice==='en-US'?'selected':''}>美音</option></select><select id="wordSpeed" aria-label="朗读速度"><option value=".85">慢速 0.85×</option><option value="1">正常 1×</option></select></div><div class="word-story">${l.paragraphs.map(p=>`<p>${highlight(p,l)}</p>`).join('')}</div><button class="btn" id="wordReadDone">${S.read[day()]?.includes(l.id)?'✓ 今日已读':'读完本篇 · +5分'}</button><p class="word-note">点击绿色词查看释义和读音。单词使用有道在线音频，文章 / 例句使用逐句系统英文语音；GPT 音频需配置服务；点击播放器 ▶ 播放并调高媒体音量。文章为原创练习故事，部分情节虚构。</p></article>
<aside class="card word-panel"><div class="eyebrow">WORD EXPLORER</div>${w?`<h2>${esc(w.word)}</h2><p>${esc(w.meaning)}</p><p class="word-note">${esc(S.cards[key(w.word)]?.status==='unknown'?'已标记：不会':'点击状态记录熟悉程度；只有回忆答对才推进复习轮次。')}</p><div class="word-flex"><button class="btn" id="wordPronounce">🔊 单词读音</button><button class="btn" id="wordSentence">听例句</button></div><p>${esc(context(l,w.word))}</p><div class="word-flex"><button class="btn" data-mark="unknown">不会 · 加入复习</button><button class="btn" data-mark="shaky">模糊</button><button class="btn" data-mark="known">熟悉</button></div>`:'<h3>从文章里选一个词</h3><p>不会的词标成金色，下次回来继续复习。</p>'}<h4>本篇目标词</h4><div class="word-list">${l.words.map(x=>`<button class="btn smallbtn" data-word="${esc(key(x.word))}">${esc(x.word)}</button>`).join('')}</div></aside></div>
<details class="card word-import"><summary>导入《雅思词汇真经》词表 / 制作自己的文章</summary><p class="word-note">内置22篇按主题原创选词，未核对书内完整词表。粘贴你拥有的词表，每行“英文单词 | 中文释义”，最多4000词。分成每组12词，逐组生成或粘贴文章。</p><textarea id="wordImportText" rows="6" placeholder="glacier | 冰川\naltitude | 海拔"></textarea><div class="word-flex"><input type="file" id="wordImportFile" accept=".txt,.csv,.tsv"><button class="btn" id="wordImport">导入词表</button></div><p id="wordImportMessage" role="status"></p><select id="wordBatch" aria-label="导入词表分组">${Array.from({length:Math.ceil(S.imported.length/12)},(_,i)=>`<option value="${i}">第${i+1}组：${esc(S.imported.slice(i*12,i*12+12).map(w=>w.word).join(', '))}</option>`).join('')}</select><div class="word-flex"><button class="btn" id="wordPrompt">复制文章提示词</button><button class="btn" id="wordGenerate">用已配置的AI生成</button></div><p class="word-note">AI按钮会把当前组的词和释义发送给设置页所选AI服务。无需API：复制提示词去你的AI聊天，生成后粘贴在下面。</p><textarea id="wordCustomText" rows="8" placeholder="粘贴原创英文文章，需包含本组每个原形词"></textarea><button class="btn" id="wordSaveArticle">检查覆盖并保存文章</button><p class="word-note"><a href="https://www.guixue.com/words/primary.shtml" target="_blank" rel="noopener">作者官方章节音频 ↗</a> · 生词、积分和文章保存在本机；换设备前请在设置页导出备份。</p></details>`;
$('#wordLesson').onchange=e=>{lessonId=e.target.value;selected='';quiz=null;render()};$('#wordDaily').onclick=()=>{lessonId=daily().id;quiz=null;render()};$('#wordVoice').onchange=e=>{S.voice=e.target.value;save()};$('#wordStop').onclick=()=>{stopAudio();if(audioDock)audioStatus('已停止播放。')};$('#wordReadAudio').onclick=()=>readArticle(l);
$('#wordReadDone').onclick=()=>{S.read[day()]??=[];if(!S.read[day()].includes(l.id)){S.read[day()].push(l.id);S.xp+=5;save()}render()};
$('#view-words').querySelectorAll('[data-word]').forEach(b=>b.onclick=()=>{selected=b.dataset.word;render()});if(w){$('#wordPronounce').onclick=()=>speak(w.word);$('#wordSentence').onclick=()=>speak(context(l,w.word));$('#view-words').querySelectorAll('[data-mark]').forEach(b=>b.onclick=()=>mark(w,b.dataset.mark,l))}
$('#wordChallenge').onclick=startQuiz;bindImport();if(quiz)renderQuiz();}
function startQuiz(){const due=Object.values(S.cards).filter(c=>c.due<=day()&&(c.status!=='known'||c.stage>0));const pool=[...due,...lesson().words.map(w=>({...w,context:context(lesson(),w.word)}))];const seen=new Set();quiz={queue:pool.filter(w=>!seen.has(key(w.word))&&seen.add(key(w.word))).slice(0,8).map((w,i)=>({...w,mode:i%2===0?'cloze':'spell'})),i:0,right:0,total:Math.min(8,new Set(pool.map(w=>key(w.word))).size),feedback:null,failed:new Set(),retry:new Set()};render();$('#wordQuiz').scrollIntoView({behavior:'smooth',block:'start'})}
function renderQuiz(){const q=quiz,box=$('#wordQuiz');if(q.i>=q.queue.length){box.innerHTML=`<h3>本轮结束 · ${q.right} 次正确回忆</h3><p>答错的词已安排明天复习。正确词按1 / 3 / 7 / 14 / 30天间隔回炉。</p><button class="btn" id="wordQuizClose">返回文章</button>`;$('#wordQuizClose').onclick=()=>{quiz=null;render()};return}
const w=q.queue[q.i];choice=w.word;const alternatives=[w.word,...lesson().words.map(x=>x.word).filter(x=>key(x)!==key(w.word)).slice(0,3)].sort(()=>Math.random()-.5);
box.innerHTML=`<div class="word-flex"><h3>回忆挑战 ${q.i+1} / ${q.queue.length}</h3><button class="btn" id="wordQuizClose">退出</button></div>${w.mode==='cloze'?`<p>${esc(w.context).replace(rx(w.word),'_____')}</p><p class="word-note">提示：${esc(w.meaning)}</p><div class="word-options">${alternatives.map(a=>`<button class="btn" data-answer="${esc(a)}" ${q.feedback?'disabled':''}>${esc(a)}</button>`).join('')}</div>`:`<p>先点击听音，再拼出单词。释义提示：${esc(w.meaning)}</p><button class="btn" id="wordQuizAudio">🔊 听单词</button><input id="wordSpell" autocomplete="off" autocapitalize="none" spellcheck="false" placeholder="输入英文" ${q.feedback?'disabled':''}><button class="btn" id="wordSubmit" ${q.feedback?'disabled':''}>检查</button>`}${q.feedback?`<div class="word-feedback"><b>${q.feedback.correct?'✓ 回忆成功':'再看一次，稍后重试'}</b><p>${esc(w.word)} · ${esc(w.meaning)}</p><p>${esc(w.context)}</p><button class="btn" id="wordFeedbackAudio">听正确读音</button></div><button class="btn primary" id="wordNext">下一题</button>`:''}`;
$('#wordQuizClose').onclick=()=>{quiz=null;render()};box.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(b.dataset.answer));if($('#wordQuizAudio')){$('#wordQuizAudio').onclick=()=>speak(w.word,true);$('#wordSubmit').onclick=()=>answer($('#wordSpell').value);$('#wordSpell').onkeydown=e=>{if(e.key==='Enter')answer(e.target.value)}}if(q.feedback){$('#wordFeedbackAudio').onclick=()=>speak(w.word);$('#wordNext').onclick=()=>{q.i++;q.feedback=null;renderQuiz()}}}
function answer(value){if(!quiz||quiz.feedback)return;const q=quiz,w=q.queue[q.i],k=key(w.word),correct=value.trim().toLowerCase()===k;let c=S.cards[k]||{word:w.word,meaning:w.meaning,context:w.context,status:'shaky',stage:0};if(correct){q.right++;if(c.lastReview!==day()){c.stage=q.failed.has(k)?0:Math.min(5,c.stage+1);c.due=new Date(Date.parse(day())+[1,1,3,7,14,30][c.stage]*86400000).toISOString().slice(0,10);c.lastReview=day();S.xp+=10}}else{q.failed.add(k);c.stage=0;c.status='unknown';c.due=new Date(Date.parse(day())+86400000).toISOString().slice(0,10);if(!q.retry.has(k)){q.retry.add(k);q.queue.push({...w,mode:'spell'})}}S.cards[k]=c;S.reviews[day()]=(S.reviews[day()]||0)+1;save();q.feedback={correct};renderQuiz()}
function batch(){return S.imported.slice(Number($('#wordBatch').value)*12,Number($('#wordBatch').value)*12+12)}
function prompt(){const b=batch();if(!b.length)throw Error('请先导入词表');return 'Write an original coherent 180–250 word IELTS learner story, B1–B2 level, about hiking, health, or a Beijing data analyst. Include every exact English word/phrase below at least once (no inflection-only substitutions). Use natural grammar and clear paragraphs. Return only the article, no title or word list. Words and meanings: '+b.map(w=>w.word+'='+w.meaning).join('; ')}
function bindImport(){const message=t=>$('#wordImportMessage').textContent=t;$('#wordImportFile').onchange=async e=>{const f=e.target.files[0];if(f)$('#wordImportText').value=await f.text()};$('#wordImport').onclick=()=>{const lines=$('#wordImportText').value.split(/\r?\n/).filter(x=>x.trim());let bad=0;const map=new Map(S.imported.map(w=>[key(w.word),w]));for(const line of lines){const m=line.trim().match(/^([a-zA-Z][a-zA-Z '-]{0,70})\s*(?:\||\t|,|，|：|:)\s*(.+)$/);if(!m){bad++;continue}const word=m[1].trim();map.set(key(word),{word,meaning:m[2].trim()})}if(map.size>4000){message('最多导入4000词，请分批。');return}S.imported=[...map.values()];save();render();$('.word-import').open=true;$('#wordImportMessage').textContent=`已存${S.imported.length}词，${bad}行未识别。选择一组制作文章。`};$('#wordPrompt').onclick=async()=>{try{const p=prompt();try{await navigator.clipboard.writeText(p);message('提示词已复制')}catch{$('#wordCustomText').value=p;message('复制不可用，提示词已放在下方，请手动复制')}}catch(e){message(e.message)}};
$('#wordGenerate').onclick=async e=>{const b=e.target;try{const p=prompt();if(!window.IELTSAI?.getKey())throw Error('请先在设置页配置AI，或复制提示词到你的AI聊天。');b.disabled=true;b.textContent='生成中…';const text=await window.IELTSAI.generateText(p,{temperature:.7,maxOutputTokens:1200});$('#wordCustomText').value=text.replace(/^```[^\n]*\n|```$/g,'').trim();message('已生成。请阅读检查，再点击检查覆盖并保存。')}catch(err){message(err.message)}finally{b.disabled=false;b.textContent='用已配置的AI生成'}};
$('#wordSaveArticle').onclick=()=>{const b=batch(),text=$('#wordCustomText').value.trim();if(!b.length||text.length<120){message('请导入词表，并粘贴一篇完整英文文章。');return}const missing=b.filter(w=>!rx(w.word).test(text));if(missing.length){message('缺少原形词：'+missing.map(w=>w.word).join(', '));return}const custom={id:'custom-'+Date.now(),theme:'我的词表',title:'My Word Expedition '+(S.custom.length+1),words:b,paragraphs:text.split(/\n+/).filter(Boolean),source:'用户导入词表 · 自定义文章，释义与内容请自行核对'};S.custom.push(custom);save();lessonId=custom.id;selected='';render();message('文章已保存')};}
function open(){window.IELTSOpenView('words');$('#topTitle').textContent='每日单词';render()}
const view=document.createElement('section');view.id='view-words';view.className='view';$('.content').append(view);for(const id of ['desktopNav','mobileNav']){const nav=$('#'+id);if(nav){const b=document.createElement('button');b.dataset.view='words';b.textContent='📖 每日单词';b.onclick=open;nav.append(b)}}
window.IELTSWordAudio={speak,systemSpeak,stop:stopAudio};window.IELTSWords={open,export:()=>S};render();
})();

(()=>{'use strict';
const $=s=>document.querySelector(s),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let history=[],record=null,recordBlob=null,recordUrl='',ttsUrl='',busy=false;
const cfg=()=>({endpoint:localStorage.getItem('ielts-voice-endpoint')||'',token:sessionStorage.getItem('ielts-voice-token')||''});
async function request(body){const c=cfg();if(!c.endpoint||!c.token)throw Error('GPT 尚未连接：请在设置页配置已部署的语音后端和访问口令。');const u=new URL(c.endpoint);if(u.protocol!=='https:')throw Error('后端必须使用 HTTPS');const res=await fetch(u.href,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+c.token},body:JSON.stringify(body),signal:AbortSignal.timeout(90000)});if(!res.ok){let msg;try{msg=(await res.json()).error}catch{}throw Error(msg||'服务请求失败 HTTP '+res.status)}return res}
function output(t){const o=$('#voiceLabOutput');if(o)o.textContent=t}
function media(blob){let box=$('#voiceGenerated');if(!box){box=document.createElement('aside');box.id='voiceGenerated';box.style.cssText='position:fixed;bottom:88px;left:12px;right:12px;background:white;border:2px solid #287568;border-radius:14px;padding:12px;z-index:60;max-width:540px;margin:auto';box.innerHTML='<b>AI 合成示范读音</b><button class="btn smallbtn" id="voiceGeneratedClose">关闭</button><audio controls playsinline style="width:100%"></audio><a class="btn smallbtn" download="ielts-example.mp3">保存 MP3</a><p>iPhone 请按 ▶。这是 AI 合成声音。</p>';document.body.append(box);$('#voiceGeneratedClose').onclick=()=>{box.querySelector('audio').pause();box.hidden=true}}if(ttsUrl)URL.revokeObjectURL(ttsUrl);ttsUrl=URL.createObjectURL(blob);box.hidden=false;box.querySelector('audio').src=ttsUrl;box.querySelector('a').href=ttsUrl;box.querySelector('audio').play().catch(()=>{})}
async function tts(text){if(!text.trim())throw Error('请先输入英文内容');window.IELTSWordAudio?.stop();output('正在生成 MP3…');const res=await request({action:'speech',text:text.slice(0,4000)});media(await res.blob());output('示范音频已生成，点击 ▶ 播放或保存 MP3。')}
function installSettings(){const host=$('#view-settings');if(!host||$('#voiceConfig'))return;const c=cfg(),card=document.createElement('article');card.className='card';card.id='voiceConfig';card.innerHTML=`<h3>GPT 口语与语音服务</h3><p>连接状态：<b id="voiceConnected">${c.endpoint&&c.token?'已配置，尚未验证':'未连接'}</b></p><p>后端负责保管 OpenAI API Key。访问口令仅在当前浏览器会话保存。生成音频、对话、录音反馈会发送相应内容到你的后端及 OpenAI，并消耗 API 额度。</p><label>后端 HTTPS 地址<input class="sprint-field" id="voiceEndpoint" placeholder="https://你的后端/api/ielts" value="${E(c.endpoint)}"></label><label>后端访问口令（不是 OpenAI API Key）<input class="sprint-field" type="password" id="voiceToken" autocomplete="off"></label><button class="btn" id="voiceSaveConfig">保存配置</button><button class="btn" id="voiceClearConfig">断开服务</button><p id="voiceConfigNote" role="status"></p>`;host.append(card);$('#voiceSaveConfig').onclick=()=>{try{const endpoint=$('#voiceEndpoint').value.trim(),u=new URL(endpoint);if(u.protocol!=='https:')throw Error('请填写 HTTPS 地址');if(!$('#voiceToken').value.trim())throw Error('请填写后端访问口令');localStorage.setItem('ielts-voice-endpoint',u.href);sessionStorage.setItem('ielts-voice-token',$('#voiceToken').value.trim());$('#voiceToken').value='';$('#voiceConnected').textContent='已配置，尚未验证';$('#voiceConfigNote').textContent='已保存。请在口语素材库生成音频。'}catch(e){$('#voiceConfigNote').textContent=e.message}};$('#voiceClearConfig').onclick=()=>{localStorage.removeItem('ielts-voice-endpoint');sessionStorage.removeItem('ielts-voice-token');$('#voiceConnected').textContent='未连接'}}
function installLab(){const host=$('#view-storybank');if(!host||$('#voiceLab'))return;const card=document.createElement('article');card.className='card';card.id='voiceLab';card.innerHTML='<h3>我的口语工作室 · 示范 / 对话 / 发音反馈</h3><p>先在下方卡片改稿并保存，再点“带到工作室”。示范朗读使用当前文本，修改后重新生成。GPT 录音反馈直接听音频；文字模式只评价表达。</p><textarea class="sprint-field" id="voiceLabText" rows="5" placeholder="粘贴英文改稿，或输入你想练的题目"></textarea><div class="sprint-actions"><button class="btn" id="voiceSystem">立即系统朗读</button><button class="btn primary" id="voiceTTS">GPT 生成示范 MP3</button><button class="btn" id="voiceChat">GPT 对话 / 追问</button><button class="btn" id="voiceResetChat">重新开始对话</button></div><p>录音仅在本机回放；点击“上传并纠正发音”才会发送。建议 20–60 秒，最长 90 秒。</p><button class="btn" id="voiceRecord">开始录音</button><audio id="voiceRecording" controls playsinline style="width:100%" hidden></audio><button class="btn" id="voiceFeedback">上传并纠正发音</button><p id="voiceLabOutput" role="status" style="white-space:pre-wrap"></p>';host.insertBefore(card,host.children[1]||null);
$('#voiceSystem').onclick=()=>window.IELTSWordAudio.systemSpeak($('#voiceLabText').value);
const run=async f=>{if(busy)return;busy=true;try{await f()}catch(e){output(e.message)}finally{busy=false}};
$('#voiceTTS').onclick=()=>run(()=>tts($('#voiceLabText').value));
$('#voiceChat').onclick=()=>run(async()=>{const text=$('#voiceLabText').value.trim();if(!text)throw Error('先填练习题目或回答');output('GPT 正在回复…');const res=await request({action:'chat',text,history});const data=await res.json();history.push({role:'user',content:text},{role:'assistant',content:data.text});history=history.slice(-12);output(data.text);$('#voiceLabText').value=''});
$('#voiceResetChat').onclick=()=>{history=[];output('已开始新对话')};
$('#voiceRecord').onclick=async()=>{try{if(record?.state==='recording'){await record.stop();return}record=await window.IELTSAI.createAudioRecorder({maxDurationMs:90000});$('#voiceRecord').textContent='停止录音';output('录音中…');const result=await record.start();recordBlob=result.blob;if(recordUrl)URL.revokeObjectURL(recordUrl);recordUrl=URL.createObjectURL(recordBlob);$('#voiceRecording').src=recordUrl;$('#voiceRecording').hidden=false;output('录音已完成。可先回放，再上传反馈。')}catch(e){output(e.message)}finally{$('#voiceRecord').textContent='开始录音'}};
$('#voiceFeedback').onclick=()=>run(async()=>{if(!recordBlob)throw Error('请先录音');output('转换音频并分析发音…');const wav=await toWav(recordBlob);const base64=await window.IELTSAI.blobToBase64(wav);const res=await request({action:'feedback',audio:base64,text:$('#voiceLabText').value.slice(0,4000)});output((await res.json()).text)});
}
async function toWav(blob){const C=window.AudioContext||window.webkitAudioContext,ctx=new C();try{const a=await ctx.decodeAudioData(await blob.arrayBuffer());const count=a.length,buf=new ArrayBuffer(44+count*2),v=new DataView(buf),put=(at,s)=>{for(let i=0;i<s.length;i++)v.setUint8(at+i,s.charCodeAt(i))};put(0,'RIFF');v.setUint32(4,36+count*2,true);put(8,'WAVE');put(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,a.sampleRate,true);v.setUint32(28,a.sampleRate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);put(36,'data');v.setUint32(40,count*2,true);for(let i=0;i<count;i++){let x=0;for(let c=0;c<a.numberOfChannels;c++)x+=a.getChannelData(c)[i];x=Math.max(-1,Math.min(1,x/a.numberOfChannels));v.setInt16(44+i*2,x<0?x*32768:x*32767,true)}return new Blob([buf],{type:'audio/wav'})}finally{await ctx.close()}}
function addCardButtons(){document.querySelectorAll('[data-save-card]').forEach(b=>{if(b.parentElement.querySelector('[data-voice-card]'))return;const x=document.createElement('button');x.className='btn smallbtn';x.dataset.voiceCard=b.dataset.saveCard;x.textContent='带到工作室 · GPT 示范 / 发音';b.after(x);x.onclick=()=>{const id=x.dataset.voiceCard;$('#voiceLabText').value=$(`[data-edit-answer="${id}"]`).value;$('#voiceLab').scrollIntoView({behavior:'smooth'});output('已带入当前改稿，可立即朗读或生成示范')}})}
const observer=new MutationObserver(()=>{installLab();addCardButtons()});if($('#view-storybank'))observer.observe($('#view-storybank'),{childList:true});installSettings();installLab();addCardButtons();
document.addEventListener('click',e=>{if(e.target.closest('[data-view="storybank"]')){installLab();addCardButtons()}if(e.target.closest('[data-view="settings"]'))installSettings()});
window.IELTSVoiceLab={tts,request};
})();

(()=>{'use strict';const $=s=>document.querySelector(s),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let saved;try{saved=JSON.parse(localStorage.getItem('ielts-bbc-study-v1')||'{}')}catch{saved={}}const persist=()=>localStorage.setItem('ielts-bbc-study-v1',JSON.stringify(saved));
function enhance(){const host=$('#bbcEpisodes');if(!host)return;host.querySelectorAll('.episode').forEach(card=>{if(card.querySelector('.bbc-study'))return;const link=Array.from(card.querySelectorAll('a')).find(a=>a.textContent.includes('来源页'));if(!link?.href.includes('bbc.co.uk'))return;const id=link.href,item=saved[id]||{},box=document.createElement('details');box.className='bbc-study';box.innerHTML=`<summary>BBC 英文原文 · 中文翻译 · 口语素材</summary><p>每日选一集学习；BBC 节目按官方发布节奏更新。完整原文请从官方页的 Transcript / PDF 获取，粘贴后可在本机保存并生成中文翻译。</p><a class="btn smallbtn" href="${E(id)}" target="_blank" rel="noopener">打开 BBC 官方原文 ↗</a><label>英文原文<textarea class="sprint-field bbc-original" rows="8" placeholder="粘贴你从官方 Transcript / PDF 取得的原文">${E(item.original||'')}</textarea></label><label>中文翻译 / 学习笔记<textarea class="sprint-field bbc-chinese" rows="8" placeholder="AI 译文需要核对，也可以粘贴自己的翻译">${E(item.translation||'')}</textarea></label><div class="sprint-actions"><button class="btn bbc-save">保存原文与翻译</button><button class="btn bbc-translate">AI 生成中文翻译</button><button class="btn bbc-copy">复制翻译提示词</button><button class="btn bbc-read">系统朗读原文</button><button class="btn bbc-speaking">提炼口语词块与复述练习</button></div><p class="bbc-note" role="status"></p>`;card.append(box);const note=t=>box.querySelector('.bbc-note').textContent=t,original=()=>box.querySelector('.bbc-original').value.trim(),translation=()=>box.querySelector('.bbc-chinese').value,store=()=>{saved[id]={original:original(),translation:translation()};persist()};box.querySelector('.bbc-save').onclick=()=>{store();note('已在本机保存')};box.querySelector('.bbc-read').onclick=()=>{if(!original())return note('请先粘贴原文');window.IELTSWordAudio.systemSpeak(original())};const prompt=()=>`请将以下由我提供的 BBC 6 Minute English 原文逐段翻译成准确自然的中文，保留说话者名和段落。不要补造缺失内容。原文：\n${original()}`;box.querySelector('.bbc-copy').onclick=async()=>{if(!original())return note('请先粘贴原文');try{await navigator.clipboard.writeText(prompt());note('提示词已复制，粘贴到你的 AI 聊天即可')}catch{note('复制不可用，请手动复制原文并要求逐段中文翻译')}};async function generate(button,p){if(!original())return note('请先粘贴原文');button.disabled=true;note('正在处理…');try{const text=await window.IELTSAI.generateText(p,{temperature:.2,maxOutputTokens:5000});box.querySelector('.bbc-chinese').value=text;store();note('AI 内容已保存，请核对译文和词义。')}catch(e){note(e.message+'；也可复制提示词到 AI 聊天。')}finally{button.disabled=false}}box.querySelector('.bbc-translate').onclick=e=>generate(e.target,prompt());box.querySelector('.bbc-speaking').onclick=e=>generate(e.target,'根据下面用户提供的英文原文，用中文讲解 6 个适合 IELTS 6.5 的词块（英文、中文、原创例句），再给一个 60 秒英文复述框架和 3 个 Part 3 追问。只依据原文，不冒充 BBC 原译文：\n'+original());});}
const host=$('#bbcEpisodes');if(host)new MutationObserver(enhance).observe(host,{childList:true});enhance();
const bank=$('#view-storybank');if(bank){const add=()=>{if($('#speakingBBCButton'))return;const b=document.createElement('button');b.id='speakingBBCButton';b.className='btn';b.textContent='BBC 6 分钟 · 听力与原文翻译';b.onclick=()=>{$('[data-view="bbc"]')?.click();$('[data-daily-feed="six"]')?.click()};bank.prepend(b)};new MutationObserver(add).observe(bank,{childList:true});add()}
})();
